# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Get the fast C bindings:
#   gem install mysql
#   (on OS X: gem install mysql -- --include=/usr/local/lib)
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

development:
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  encoding: utf8
  host: localhost
  database: sds_development
  username: root
  password: 

test:
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  encoding: utf8
  host: localhost
  database: sds_test
  username: root
  password: 
  socket: /tmp/mysql.sock

production:
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  encoding: utf8
  host: localhost
  database: sds_production
  username: root
  password: 
  socket: /tmp/mysql.sock

sunflower:
  adapter: mysql
  host: database.concord.org
  username: rails
  password: 
  database: sunflower
