--- 
:delivery_method: :test
:host: saildataservice.org
:smtp: 
  :password: your_smtp_password
  :address: mail.saildataservice.org
  :port: 25
  :authentication: :login
  :user_name: your_smtp_username
  :domain: saildataservice.org
